### ISSUE TITLE
Icon buttons in window bar ?

### ISSUE THREAD

**Issue by olivierfaure** [miyako/4d-plugin-window-control-v2#1]
Hi, do you try to put action buttons in window title bar as macOS do now ? could it be possible in 4D ? thx :)

Icons in title bar in Pages, Numbers are too small, a don't find a way to have it as big as the finder could do.

**Comment by 4D-JP** [comment]
I don't think it is possible, or to say the least, easy. You need to add specialised views to the window hierarchy and implement MVC in swift or objective-c. It would be a lot of work to translate the cocoa concept to the 4D language, which would look like a hack from Apple's point of view (they want you to develop with Xcode, not 4D) and it may quickly become unstable or dysfunctional with the next macOS update. Not to mention the fact that its absence would be all apparent on Windows.

**Comment by olivierfaure** [comment]
Thx :) A workaround could be the possibility of having a type of window with only coloured button but without title

**Comment by miyako** [comment]
well, you can remove the separator with https://github.com/miyako/4d-plugin-apple-window-title-bar and all windows kind of look this way in Big Sur, so yes, I guess you can fake it that way...

**Comment by olivierfaure** [comment]
Very nice :-)

Thx

Olivier

**Comment by olivierfaure** [comment]
The only issue I have with the plug-in is that bar continue to move when i clic on it (normal), even if there is a 4D button, a drop-menu can be opened and the window move in the same way if we keep mouse down but it's ok. 

Olivier Faure
Responsable Développements



41 rue Yves Montand, 34080 Montpellier
www.noma.fr
olivier@noma.fr
04 67 75 44 62

**Comment by miyako** [comment]
The plugin is a simple wrapper of [titlebarAppearsTransparent](https://developer.apple.com/documentation/appkit/nswindow/1419167-titlebarappearstransparent?language=objc).

Excel puts icons at the same level as the title bar, and you can not drag the window if you click them. I guess this is the expected behaviour, but as a consequence you have little space left to actually drag the window.

<img width="377" alt="excel" src="https://user-images.githubusercontent.com/1725068/100372038-05ed0800-304c-11eb-8e53-257f75ed4a32.png">

Anyway, I see that the plugin is old, I will update it for notarisation.

**Comment by miyako** [comment]
updated https://github.com/miyako/4d-plugin-apple-window-title-bar/releases/tag/1.0.0

**Comment by olivierfaure** [comment]
Hi, thank you for the update, is there modifications in features ? if I keep mouse down while moving on a button, it still moves the window but it's not important, it works well 👍

**Comment by miyako** [comment]
> modifications in features ?

no, sorry about that.
